name: Docker Development Build and Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build and test the frontend Docker image
      - name: Build and test frontend
        working-directory: ./frontend
        run: |
          docker build -t frontend-dev .
          docker run -d --name frontend-dev-container frontend-dev
          docker logs frontend-dev-container

      # Step 4: Build and test the backend Docker image
      - name: Build and test backend
        working-directory: ./backend
        run: |
          docker build -t backend-dev .
          docker run -d --name backend-dev-container -e MONGO_URI=mongodb://mongo:27017/Pi-2025 backend-dev
          docker logs backend-dev-container

      # Step 5: Clean up containers
      - name: Clean up
        run: |
          docker stop frontend-dev-container backend-dev-container
          docker rm frontend-dev-container backend-dev-container